version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test-server:
    executor: node/default
    working_directory: ~/project/server
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
          cache-path: node_modules
      - run: yarn test
workflows:
  node-tests:
    jobs:
      - test-server
