version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test-server:
    executor: node/default
    working_directory: ~/project/server
    steps:
      - checkout
      - node/install-packages:
          cache-path: node_modules
      - run: yarn test
workflows:
  node-tests:
    jobs:
      - test-server
