version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  test-server:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/server
          pkg-manager: yarn
          cache-path: ~/project/server/node_modules
          cache-version: v2
      - run: mkdir ~/junit
      - run:
          name: Run Unit Tests
          command: yarn run coverage
          working_directory: ~/project/server
          when: always
      - store_test_results:
          path: ~/project/server/test-results
      - store_artifacts:
          path: ~/project/server/test-results
  deploy:
    executor: node/default
    parameters:
      app:
        type: string
      token:
        type: string
    steps:
      - checkout
      - run: yarn add caprover
      - run: >
          node_modules/.bin/caprover deploy -h https://captain.caprover.vormadal.com 
          -b $CIRCLE_BRANCH 
          -c ./captain-definition 
          --appToken << parameters.token >> 
          -a "<< parameters.app >>"
  verify:
    executor: node/default
    parameters:
      app:
        type: string
    steps:
      - checkout
      - run: yarn add caprover
      - run: node ./scripts/waitForDeploymentCompletion.js appName=<< parameters.app >> password=${CAPTAIN_PASSWORD} cwd=/home/circleci/project/node_modules/.bin

workflows:
  node-tests:
    jobs:
      - test-server
      - deploy:
          name: deploy test
          token: $TEST_APP_TOKEN
          app: test-tutlid-booking
          requires:
            - "test-server"
          filters:
            branches:
              only:
                - master
      - verify:
          name: verify test
          app: test-tutlid-booking
          requires:
            - "deploy test"
      - approve-deployment:
          type: approval
          requires:
            - "verify-test"
      - deploy:
          name: deploy production
          token: $APP_TOKEN
          app: tutlid-booking
          requires: 
            - "approve-deployment"