version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test-server:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/server
          pkg-manager: yarn
          cache-path: ~/project/server/node_modules
          cache-version: v2
      - run: mkdir ~/junit
      - run:
          name: Run Unit Tests
          command: yarn test
          working_directory: ~/project/server
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/project/server/junit
      - store_artifacts:
          path: ~/project/server/junit
workflows:
  node-tests:
    jobs:
      - test-server
