version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test-server:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/server
          pkg-manager: yarn
          cache-path: ~/project/server/node_modules
      - run: yarn --cwd ~/project/server test
workflows:
  node-tests:
    jobs:
      - test-server
