version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test-server:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/server
          pkg-manager: yarn
          cache-path: ~/project/server/node_modules
          cache-version: v2
      - run:
          command: |
            ls
            cd node_modules
            ls
            node -v
            yarn -v
          name: Checking folder structure
          working_directory: ~/project/server
      - run: yarn --cwd ~/project/server run test
workflows:
  node-tests:
    jobs:
      - test-server
